### ISSUE TITLE
Error message on jupyter notebook

### ISSUE THREAD

**Issue by sciencestand** [SuLab/Applied-Bioinformatics#14]
Hi...I saved and restarted the kernel as the update comment suggested, then I tried to validate the homework running "validate", I'm getting this error message, and I found this resource  (https://github.com/jupyter/nbgrader/issues/883), but I'm not sure if I have the ability to fix the problem on my side:
There was an error running the validate command:

Traceback (most recent call last):
  File "/opt/applications/python/3.6.3/gnu/lib/python3.6/site-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 46, in validate_notebook
    result = validator.validate(fullpath)
  File "/opt/applications/python/3.6.3/gnu/lib/python3.6/site-packages/nbgrader/validator.py", line 311, in validate
    nb = self._preprocess(nb)
  File "/opt/applications/python/3.6.3/gnu/lib/python3.6/site-packages/nbgrader/validator.py", line 290, in _preprocess
    nb, resources = pp.preprocess(nb, resources)
  File "/opt/applications/python/3.6.3/gnu/lib/python3.6/site-packages/nbgrader/preprocessors/checkcellmetadata.py", line 16, in preprocess
    raise ValidationError(msg)
jsonschema.exceptions.ValidationError: Notebook failed to validate; the nbgrader metadata may be corrupted.

**Comment by sciencestand** [comment]
It seems an issue that it is related to the cells which were generated by the owner of the homework, if these cell manipulated in someway, the error will popup, @NicoleMadrazo pointed out that she experienced this before. I do rearrange cells all the time to organize my thought when approaching a question, but I also did copy testthat cell  and did paste it closer to the end of the homework to make it easy to run after connecting to VPN and restarting the kernel.
